const submittedApplication = [
  {
    id: 1,
    name: 'Job 1',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 2,
    name: 'Job 2',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 3,
    name: 'Job 3',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 4,
    name: 'Job 4',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 5,
    name: 'Job 5',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 6,
    name: 'Job 6',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 7,
    name: 'Job 7',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 8,
    name: 'Job 8',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 9,
    name: 'Job 9',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 10,
    name: 'Job 10',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 11,
    name: 'Job 11',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'denied',
  },
  {
    id: 12,
    name: 'Job 12',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 13,
    name: 'Job 13',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 14,
    name: 'Job 14',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 15,
    name: 'Job 15',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'applied',
  },
  {
    id: 16,
    name: 'Job 16',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'denied',
  },
  {
    id: 17,
    name: 'Job 17',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'denied',
  },
  {
    id: 18,
    name: 'Job 18',
    position: 'Test Position',
    jobId: 'job id string',
    link: 'link.com',
    date: '01/01/2024',
    status: 'interview',
  },
];

export { submittedApplication };
